version: '1.0'
stages:
  - prepare
  - build
steps:
  main_clone:
    title: Cloning main repository...
    stage: prepare
    type: git-clone
    repo: 'jlmayorga/spring-boot-demo'
    revision: main
    git: github
  build_app_image:
    title: Building Docker Image
    type: build
    stage: build
    image_name: jlmayorga/spring-boot-demo
    working_directory: ./
    tags:
      - "${{CF_SHORT_REVISION}}"
    dockerfile: Dockerfile
  scan_code:
    title: Source security scan
    stage: verify
    image: 'snyk/snyk-cli:maven-3.6.3_java11'
    commands:
      - snyk monitor
    scan_image:
      title: Container security scan
      stage: verify
      image: 'aquasec/trivy'
      commands:
        - trivy image docker.io/jlmayorga/spring-boot-demo:${{CF_SHORT_REVISION}}
