version: "1.0"
stages:
  - "prepare"
  - "verify"
  - "deploy"

steps:
  main_clone:
    title: "Cloning repository"
    type: "git-clone"
    repo: 'jlmayorga/spring-boot-demo'
    revision: "${{CF_REVISION}}"
    stage: "prepare"
    git: github

  run_unit_tests:
    title: Compile/Unit test
    stage: prepare
    image: 'maven:3.8-openjdk-11'
    commands:
      - mvn -Dmaven.repo.local=/codefresh/volume/m2_repository package
  build_app_image:
    title: Building Docker Image
    type: build
    stage: prepare
    image_name: jlmayorga/spring-boot-demo
    working_directory: ./
    tag: '${{CF_BRANCH}}'
    dockerfile: Dockerfile
  scan_code:
    title: Source security scan
    stage: verify
    image: 'snyk/snyk-cli:maven-3.6.3_java11'
    commands:
      - snyk monitor
  scan_image:
    title: Container security scan
    stage: verify
    image: 'aquasec/trivy'
    commands:
      - trivy image docker.io/jlmayorga/spring-boot-demo:${{CF_BRANCH}}
  run_integration_tests:
    title: Integration tests
    stage: verify
    image: maven:3.8-openjdk-11
    commands:
      - mvn -Dmaven.repo.local=/codefresh/volume/m2_repository verify -Dserver.host=http://my-spring-app -Dsonar.organization=jlmayorga
    services:
      composition:
        my-spring-app:
          image: '${{build_app_image}}'
          ports:
            - 8080
      readiness:
        timeoutSeconds: 30
        periodSeconds: 15
        image: byrnedo/alpine-curl
        commands:
          - "curl http://my-spring-app:8080/hello/"
  sonar_scan:
    title: Sonar Scan
    stage: verify
    image: 'maven:3.8-openjdk-11'
    commands:
      - mvn -Dmaven.repo.local=/codefresh/volume/m2_repository org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.login=${{SONAR_TOKEN}} -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=jlmayorga -Dsonar.projectKey=xyz.jlmayorga:spring-boot-demo

  call_cd_pipeline:
    title: Deploy dev environment
    stage: "deploy"
    type: "codefresh-run"
    arguments:
      PIPELINE_ID: 62852a80024748be4baa0659
      VARIABLE:
        - CF_BRANCH=${{CF_BRANCH}}
        - CF_REVISION=${{CF_REVISION}}
        - CF_BRANCH_TAG_NORMALIZED=${{CF_BRANCH_TAG_NORMALIZED}}
        - CF_PULL_REQUEST_NUMBER=${{CF_PULL_REQUEST_NUMBER}}
