version: '1.0'
stages:
  - prepare
  - build
steps:
  main_clone:
    title: Cloning main repository...
    stage: prepare
    type: git-clone
    repo: 'jlmayorga/spring-boot-demo'
    revision: main
    git: github
  build_app_image:
    title: Building Docker Image
    type: build
    stage: build
    image_name: jlmayorga/spring-boot-demo
    working_directory: ./
    tags:
      - "${{CF_BRANCH_TAG_NORMALIZED_LOWER_CASE}}"
      - "${{CF_SHORT_REVISION}}"
    dockerfile: Dockerfile
