version: '1.0'
stages:
  - prepare
  - build
  - verify
  - push
steps:
  main_clone:
    title: Cloning main repository...
    stage: prepare
    type: git-clone
    repo: 'jlmayorga/spring-boot-demo'
    revision: main
    git: github
  build_app_image:
    title: Building Docker Image
    type: build
    stage: build
    disable_push: true
    image_name: jlmayorga/spring-boot-demo
    working_directory: ./
    tags:
      - "${{CF_SHORT_REVISION}}"
    dockerfile: Dockerfile
  scan_code:
    title: Source security scan
    stage: verify
    image: 'snyk/snyk-cli:maven-3.6.3_java11'
    commands:
      - env | sort
      - snyk auth
      - snyk monitor
  scan_image:
    title: Container security scan
    stage: verify
    image: 'aquasec/trivy'
    commands:
      - trivy image docker.io/jlmayorga/spring-boot-demo:${{CF_SHORT_REVISION}}
  push_to_registry:
    stage: push
    type: push
    title: Pushing container image to registry
    candidate: ${{build_app_image}}
    tag: ${{CF_SHORT_REVISION}}

