version: '1.0'
stages:
  - prepare
  - build
  - verify
  - push
steps:
  main_clone:
    title: Cloning main repository...
    stage: prepare
    type: git-clone
    repo: 'jlmayorga/spring-boot-demo'
    revision: main
    git: github
  build_app_image:
    title: Building container image
    type: build
    stage: build
    disable_push: true
    image_name: jlmayorga/spring-boot-demo
    working_directory: ./
    tags:
      - "${{CF_SHORT_REVISION}}"
    dockerfile: Dockerfile
  scan_code:
    title: Source security scan
    stage: verify
    image: 'snyk/snyk-cli:maven-3.6.3_java11'
    commands:
      - snyk monitor
      - snyk test --severity-threshold=high
    on_success:
      metadata:
        set:
          - '${{build_app_image.imageId}}':
              - CF_QUALITY: true
    on_fail:
      metadata:
        set:
          - '${{build_app_image.imageId}}':
              - CF_QUALITY: false
  scan_image:
    title: Container security scan
    stage: verify
    image: 'aquasec/trivy'
    commands:
      - trivy image ${{build_app_image.imageId}}
    on_success:
      metadata:
        set:
          - '${{build_app_image.imageId}}':
              - SECURITY_SCAN: true
    on_fail:
      metadata:
        set:
          - '${{build_app_image.imageId}}':
              - SECURITY_SCAN: false
  push-to-registry:
    title: Pushing to container image registry
    stage: push
    type: push
    candidate: '${{build_app_image}}'
    tag: '${{CF_SHORT_REVISION}}'

